import { readFileSync } from "node:fs";
import { join } from "node:path";

import { render, screen, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it } from "vitest";

import { Breadcrumbs } from "./Breadcrumbs";

describe("Breadcrumbs", () => {
  it("removes consecutive duplicate labels and marks the current page", () => {
    render(
      <MemoryRouter>
        <Breadcrumbs
          items={[
            { label: "Inicio", to: "/" },
            { label: "Aceites de Oliva y Vinos", to: "/desde-fp/INA02M" },
            { label: "Dónde estudiar", to: "/donde-estudiar/INA02M" },
            { label: "Dónde estudiar" },
          ]}
        />
      </MemoryRouter>,
    );

    const navigation = screen.getByRole("navigation", {
      name: "Ruta de navegación",
    });
    expect(
      within(navigation)
        .getAllByRole("listitem")
        .map((item) => item.textContent?.trim()),
    ).toEqual(["Inicio", "Aceites de Oliva y Vinos", "Dónde estudiar"]);
    expect(within(navigation).getByText("Dónde estudiar")).toHaveAttribute(
      "aria-current",
      "page",
    );
    expect(
      within(navigation).getByRole("link", {
        name: "Aceites de Oliva y Vinos",
      }),
    ).toHaveAttribute("href", "/desde-fp/INA02M");
  });

  it("renders N items with separators only generated by a single CSS rule", () => {
    const { container } = render(
      <MemoryRouter>
        <Breadcrumbs
          items={[
            { label: "Inicio", to: "/" },
            {
              label: "Auxiliares de enfermería hospitalaria",
              to: "/desde-ocupacion/occupation%3Acno11%3A5611",
            },
            {
              label: "Ofertas relacionadas",
              to: "/desde-ocupacion/occupation%3Acno11%3A5611/ofertas",
            },
            { label: "Datos abiertos" },
          ]}
        />
      </MemoryRouter>,
    );

    const navigation = within(container).getByRole("navigation", {
      name: "Ruta de navegación",
    });
    const items = within(navigation).getAllByRole("listitem");
    expect(items).toHaveLength(4);

    // Separators are never real DOM content: a single generated rule is the
    // only source, so 4 items expose at most 3 visual separators.
    expect(navigation.textContent).not.toContain("/");
    for (const item of items) {
      expect(item.textContent).not.toContain("/");
    }

    const ruleBodies = ["salida.css", "visualRefresh.css"].map((file) =>
      readFileSync(join(process.cwd(), "src/styles", file), "utf8"),
    );
    const separatorRules = ruleBodies.flatMap((css) =>
      [...css.matchAll(/\.breadcrumbs[^{}]*\{([^}]*)\}/gu)]
        .filter((rule) => /content:\s*"›"/u.test(rule[1]))
        .map((rule) => rule[0]),
    );
    expect(separatorRules).toHaveLength(1);
    expect(separatorRules[0]).toMatch(/li\s*\+\s*li::before/u);
  });
});
